version: 0.1.0-{build}-{branch}-ci

image: ubuntu

configuration: Release

install:
- curl -s https://codecov.io/bash
- cd Source && dotnet restore

build:
  project: Source/MetaPrograms.sln
  verbosity: minimal
  publish_nuget: true

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'

test_script:
- chmod x+u ./Build/test.sh
- ./Build/test.sh
