version: 0.1.0-{build}-{branch}-ci

image: ubuntu

configuration: Release

environment:
  CODECOV_TOKEN:
    secure: 0Ir8q06A8QxsknKh0JLhTA==

install:
- pip install --user codecov
- cd $APPVEYOR_BUILD_FOLDER/Build && chmod u+x test.sh
- cd $APPVEYOR_BUILD_FOLDER/Source && dotnet restore

build:
  project: Source/MetaPrograms.sln
  verbosity: minimal
  publish_nuget: true

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'

test_script:
- $APPVEYOR_BUILD_FOLDER/Build/test.sh

after_test:
- codecov
