version: 0.1.0-{build}-{branch}-ci

image: ubuntu

configuration: Release

install:
- cd Build && curl -s https://codecov.io/bash -o codecov.sh && chmod u+x codecov.sh && chmod u+x test.sh && cd ..
- cd Source && dotnet restore

build:
  project: Source/MetaPrograms.sln
  verbosity: minimal
  publish_nuget: true

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'

test_script:
- cd Build && ./test.sh
