version: 0.1.0-{build}-{branch}-ci

image: ubuntu1804

configuration: Release

install:
- cd Source && dotnet restore

build:
  project: Source/MetaPrograms.sln
  verbosity: minimal
  publish_nuget: true

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
